### ISSUE TITLE
Initial Issue

### ISSUE THREAD

**Issue by MiniGrayGay** [KimigaiiWuyi/fastapi_genshin_map#1]
是不是缺了`requirements.txt`，要装 httpx、sklearn、rollbar、uvicorn、fastapi、shapely

**Comment by MiniGrayGay** [comment]
`pip3 install fastapi rollbar uvicorn pillow httpx numpy shapely sklearn`

**Comment by monsterxcn** [comment]
5905b4aebe7ec91073966a6b6b8cde2575e80d9e 已添加 `requirements.txt`
